// " James Gosling " at Sun Microsystems (now Oracle)
// Java is a high-level, object-oriented,
// platform-independent programming language. 

// created Java in 1995.
// Java is designed to have as few implementation dependencies as possible. 
// Imagine Java as a super chef 🍳 who writes one recipe (code) and it can be cooked on any stove (Windows, Mac, Linux). That’s WORA:
// 🗣️ "Write Once, Run Anywhere!"
// Java is used for building web applications, mobile apps, games, and more.
// Multithreaded :Does many tasks at once (like your mom) 😅
// Robust :Handles errors well – it’s emotionally strong 💪
//Compare Java with C++ in one sentence : C++ offers low-level memory control and high performance, making it suitable for system programming and resource-intensive applications, while Java prioritizes platform independence and ease of development through automatic memory management and a simpler syntax, ideal for enterprise and web applications.

class Bio{
    public static void main(String[] args){
        System.out.println("Hi! I'm Rohit.");
    }
}

// Question	Rockstar Answer
// What is Java? =>	Java is a high-level, object-oriented, platform-independent language created by James Gosling in 1995.
// Why is Java platform-independent => Because Java code is compiled into bytecode, which the JVM can run on any platform.
// What is bytecode? => It's the intermediate code generated by the Java compiler, which can run on any system with JVM.
// What is the JVM? => JVM (Java Virtual Machine) executes Java bytecode and provides a runtime environment.
// Is Java 100% object-oriented? => No, because it supports primitive data types like int, char, etc.